sonar.projectKey = asadrafi1221_MERNSPACE_auth_service
sonar.organization = asadcodes
sonar.projectName = MERNSPACE_auth_service
sonar.sources = src
sonar.test = tests
sonar.exclusions=**/node_modules/**,**/dist/**,**/migration/**,**/build/**
sonar.qualitygate.wait = true
sonar.javascript.lcov.reportPaths = ./coverage/lcov.info
sonar.scm.exclusions.disabled = true